### ISSUE TITLE
Report Generation does not work anymore with SpecFlow 3

### ISSUE THREAD

**Issue by bertrandpons** [mmajcica/SpecFlowReportGeneratorTask#3]
Hi,

I get the following error when I want to generate html report from trx file:

```
Consoler.NConsolerException: Object reference not set to an instance of an object. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TechTalk.SpecFlow.Configuration.JsonConfig.JsonConfigurationLoader.LoadJson(SpecFlowConfiguration specFlowConfiguration, String jsonContent)
   at TechTalk.SpecFlow.Configuration.ConfigurationLoader.Load(SpecFlowConfiguration specFlowConfiguration, ISpecFlowConfigurationHolder specFlowConfigurationHolder)
   at TechTalk.SpecFlow.Generator.Configuration.GeneratorConfigurationProviderExtensions.LoadConfiguration(IGeneratorConfigurationProvider configurationProvider, SpecFlowConfigurationHolder configurationHolder)
   at TechTalk.SpecFlow.Generator.Project.MsBuildProjectReader.LoadAppConfig(SpecFlowProject specFlowProject, XDocument xDocument, String projectFolder, Boolean newProjectSystem)
   at TechTalk.SpecFlow.Generator.Project.MsBuildProjectReader.ReadSpecFlowProject(String projectFilePath)
   at TechTalk.SpecFlow.Reporting.NUnitExecutionReport.NUnitBasedExecutionReportGenerator.GenerateAndTransformReport()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NConsoler.Consolery.InvokeMethod(MethodInfo method)
   --- End of inner exception stack trace ---
   at NConsoler.Consolery.InvokeMethod(MethodInfo method)
   at NConsoler.Consolery.Run(Type targetType, String[] args, IMessenger messenger)
```

**Comment by gkalnytskyi** [comment]
Specflow dev's removed report generation from Specflow 3. I am also curious if @mmajcica is going to support Specflow 3.

**Comment by Tuely** [comment]
I am getting this error

![image](https://user-images.githubusercontent.com/29451624/66654689-b58dcd80-ec32-11e9-86da-e544dbf74b2a.png)
